using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataAvail.SqlConverter.XmlFormatter
{
    /// <summary>
    /// Only tag & name
    /// </summary>
    public class XmlFormatterOptionsA : XmlFormatterOptions
    {
        public XmlFormatterOptionsA()
        {
            //Table
            this.tableOptions.schemeAttr = null;

            //Field
            this.fieldOptions.defaultValueAttr = null;
            this.fieldOptions.isNullableAttr = null;
            this.fieldOptions.isPkAttr = null;
            this.fieldOptions.isPkAutoGeneratedAttr = null;
            this.fieldOptions.sizeAttr = null;
            this.fieldOptions.typeAttr = null;

            //Relation
            this.relationOptions.childFieldAttr = null;
            this.relationOptions.childTableAttr = null;
            this.relationOptions.parentFieldAttr = null;
            this.relationOptions.parentTableAttr = null;
        }
    }
}
